#!/bin/bash
if [ "" = "$1" ]; then
	echo "(function(require,module,exports){"
else
	echo "fin.Hypergrid.modules['$1']=(function(require,module,exports){"
fi
cat # stream stdin
echo ";return module.exports})(fin.Hypergrid.require,fin.$={},fin.$.exports={});"
echo "delete fin.$;"
